<div>
    <div class="status-image"><div class="analyzer-error"></div></div>
    <div class="status-details">Something went wrong!</div>
    <div class="status-message">
        <p style="padding: 0 8px;">Please check the sizes you have entered or try to upload your image again.  If you see this error again please contact us at service@magicmurals.comor 1-877-448-7295 for assistance.</p><br />
        <div class="status-buttons">
            <a href="/custom-wall-murals.html" class='button'><span>Upload New Image</span></a>
        </div>
    </div>
</div>