<div>
    <div class="status-image">
        <div class="analyzer-fair"></div>
    </div>
    <div class="status-details">
        <p>The image resolution is "Fair" for the proposed size wall mural.</p>
    </div>
    <div class="status-message">
        <div class="status-buttons clearer">
            <div class="grid12-12">
                <div class="grid12-4">
                    <a href="/custom-wall-murals.html" class='button'><span>Upload New Image</span></a>
                    <p>Select a new image with higher resolution.</p>
                </div>
                <div class="grid12-4">
                    <a href="javascript:loadSubmitReview();" id="review-submit-btn-new" class='button'><span>Submit for Review</span></a>
                    <p>Let our image experts review. If your photo won&rsquo;t work we can find one that will.</p>
                </div>
                <div class="grid12-4">
                    <a href="javascript:void(0);" id="" class="button" data-remodal-target="modal"><span>Add to Cart &raquo;</span></a>
                    <p>Proceed if you&rsquo;d like to order using this image. <em>(All files are reviewed by our image experts before printing.)</em></p>
                </div>
            </div>
        </div>
    </div>
</div>