<div>
    <div class="status-image"><div class="analyzer-good"></div></div>
    <div class="status-details">
        <p><b>Congratulations!</b><br />The image resolution exceeds our requirements for the proposed size wall mural.</p>
        <p>Click "Add to Cart" to proceed to checkout.</p>
    </div>
    <div class="grid12-12">
        <div class="status-message">
            <p style="padding: 0 8px;">After receiving your order, a member of our production team will review the content of your image and contact you if there is an issue.  Otherwise your mural should be ready to ship within 2 to 3 business days from order date.</p><br />
            <div class="status-buttons">
                <a href="javascript:void(0);" id="" class="button" data-remodal-target="modal"><span>Add to Cart &raquo;</span></a>
            </div>
        </div>
    </div>
</div>