<div>
    <div class="status-image"><div class="analyzer-poor"></div></div>
    <div class="status-details">
        <p>The image resolution is poor quality for the proposed size wall mural.</p>
    </div>
    <div class="status-message">
        <p style="padding: 0 8px;">We do not recommend printing a mural of this image at the requested size.  <br />Click &quot;Upload New Image&quot; to select another image to analyze or click “Contact Us” for further assistance in selecting a high resolution image for your custom mural.</p><br />
        <div class="status-buttons">
            <a href="/custom-wall-murals.html" class='button'><span>Upload New Image</span></a> <a href="/contact" class='button'><span>Contact Us</span></a>
        </div>
    </div>
</div>