<?php


$media_folder = $this->getMediaDirectory() . "logos/";

$helper = $this->getBrandHelper();

$files = array();

if (is_dir($media_folder)) {
    if ($dh = opendir($media_folder)) {
        while (($file = readdir($dh)) !== false) {
            if ( $file != "." && $file != "..") {
                $files[] = $file;
            }
        }
        closedir($dh);
    }
}
asort($files);

?>

<?php
	$sliderClasses = '';
	$imgClasses = '';

	//Slider parameters
	//--------------------------------------------------------------
	//Responsive mode on/off
	$isResponsive = $this->getIsResponsive(); //param: is_responsive
	if ($isResponsive === NULL) //Param not set
	{
		$isResponsive = true; //IMPORTANT: enabled by default
	}

	//Assign number of items in a row to specific viewport width
	$breakpoints = $this->getBreakpoints(); //param: breakpoints
	if ($breakpoints === NULL) //Param not set
	{
		$breakpoints = '[0, 1], [320, 2], [480, 2], [768, 4], [960, 6], [1280, 6]'; //Set default breakpoints
	}

	//Number of items in a row displayed if responsive mode is off
	$showItems = $this->getShowItems(); //param: show_items
	if (!$showItems) //Param not set or equals zero
	{
		$showItems = 6; //Set default number of items
	}

	//Pagination on/off
	$pagination = $this->getPagination(); //param: pagination

	//Slider timeout. Set to enable automatic scrolling.
	$timeout = $this->getTimeout(); //param: timeout
	if ($timeout === NULL) //Param not set
	{
		$timeout = intval($helper->getCfg('slider/timeout'));
	}
	else
	{
		$timeout = intval($timeout);
	}
    $timeout = 600;

	//Number of items that should move on scrolling
	$move = $this->getMove(); //param: move
	if ($move === NULL) //Param not set
	{
		$move = 0; //By default scroll all visible items
	}
	else
	{
		$move = intval($move);
	}

	//If set, slider will loop.
	$loop = $this->getLoop(); //param: loop
	if ($loop === NULL) //Param not set
	{
		$loop = $helper->getCfg('slider/loop');
	}

	//Scrolling speed
	$speed = intval($helper->getCfg('slider/speed'));

	//Speed (automatic scrolling / pagination)
	$autoSpeed = intval($helper->getCfg('slider/auto_speed'));

	//Pause slider on mouse hover
	$pause = $helper->getCfg('slider/pause');

	//Lazy loading
	$lazy = $helper->getCfg('slider/lazy');

	//Slider classes
	//--------------------------------------------------------------
	if($isResponsive)
	{
		$sliderClasses .= ' itemslider-responsive';
	}

	$sliderId = "itemslider-client-logos-{$this->getFrontendHash()}";
?>
<?php

	//If lazy loading enabled
	if ($lazy)
	{
		$srcAttribute = 'data-src';
		$imgClasses = 'class="lazyOwl"';
	}
	else
	{
		$srcAttribute = 'src';
		$imgClasses = '';
	}
?>

<h3 class="client-logos section-title padding-right">Just a few of our many clients</h3>
<div class="itemslider-wrapper client-logos-slider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1 slider-pagination1-centered">
	<div id="<?php echo $sliderId; ?>" class="itemslider<?php if($sliderClasses) echo $sliderClasses; ?> client-logos-slider">
	<?php foreach ($files as $t): ?>
		<?php
		$brandImageUrl = "/pub/media/logos/".$t;
		$brandDetailsHtml = '';

        if ($brandImageUrl)
        {
            //Build image tag
            $brandDetailsHtml = "<img {$imgClasses} {$srcAttribute}=\"{$brandImageUrl}\" />";
        }
        
		?>
		<?php if ($brandDetailsHtml): ?>

			<div class="item">
				<?php echo $brandDetailsHtml; ?>
			</div>

		<?php endif; ?>
	<?php endforeach; ?>
	</div> <!-- end: itemslider -->
</div> <!-- end: itemslider-wrapper -->
<script type="text/javascript">
require(['jquery', 'owlcarousel'], function(){
	jQuery(function($) {

		var owl = $('#<?php echo $sliderId; ?>');
		owl.owlCarousel({

		<?php if ($lazy): ?>
			lazyLoad: true,
		<?php endif; ?>

		<?php if (!$isResponsive): ?>
			responsive: false,
			items: <?php echo $showItems; ?>,
		<?php else: ?>
			itemsCustom: [ <?php echo $breakpoints; ?> ],
			responsiveRefreshRate: 50,
		<?php endif; ?>

		<?php if ($speed): ?>
			slideSpeed: <?php echo $speed; ?>,
		<?php endif; ?>

		<?php if ($autoSpeed): ?>
			paginationSpeed: <?php echo $autoSpeed; ?>,
		<?php endif; ?>

		<?php if ($move !== 1): ?>
			scrollPerPage: true,
		<?php endif; ?>

		<?php if ($timeout): ?>
			autoPlay: <?php echo $timeout; ?>,
		<?php endif; ?>
        autoPlay: true,

		<?php if ($pause): ?>
			stopOnHover: true,
		<?php endif; ?>

		<?php if ($loop): ?>
			rewindNav: true,
			rewindSpeed: 800,
		<?php else: ?>
			rewindNav: false,
		<?php endif; ?>

		<?php if ($pagination): ?>
			pagination: true,
			paginationSpeed: 800,
		<?php else: ?>
			pagination: false,
		<?php endif; ?>

			navigation: true,
			navigationText: false

		}); //end: owl

	});
});
</script>
