<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

if($this->getRequest()->getFullActionName() != 'catalog_product_view') {
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
	
	$finalPrice = $block->getSaleableItem()->getPriceModel()->getFinalPrice(1,$block->getSaleableItem()); 
	$regPrice = $block->getSaleableItem()->getPrice();

	/* get the product info for min size */
	$mini_sqft = $product->getData('mini_sq_ft');
	$small_sqft = $product->getData('small_sq_ft');
	$med_sqft = $product->getData('medium_sq_ft');
	$large_sqft = $product->getData('large_sq_ft');
	$xlarge_sqft = $product->getData('x_large_sq_ft');
	$clear_sqft = $product->getData('clearance_sq_ft');

	$minSqft = 0;

	if ($minSqft == 0 && $mini_sqft > 0) {
		$minSqft = $mini_sqft;
	} elseif ($minSqft == 0 && $small_sqft > 0) {
		$minSqft = $small_sqft;
	} elseif ($minSqft == 0 && $med_sqft > 0) {
		$minSqft = $med_sqft;
	} elseif ($minSqft == 0 && $large_sqft > 0) {
		$minSqft = $large_sqft;
	} elseif ($minSqft == 0 && $xlarge_sqft > 0) {
		$minSqft = $xlarge_sqft;
	} elseif ($minSqft == 0 && $clear_sqft > 0) {
		$minSqft = $clear_sqft;
	} 

	$finalPrice = $finalPrice * $minSqft;
	$regPrice = $regPrice * $minSqft;

	$priceBlockTmp = '<span class="{class}">
	<span class="price-container price-final_price tax weee">
				<span class="price-label">{label}</span>
			<span id="{id}" data-price-amount="{amount}" data-price-type="{type}" class="price-wrapper ">
			<span class="price">${format_amount}</span></span>
			</span>
		</span> ';
	$priceBlockRep = array();
	$priceBlockSearch = array(
		'{class}',
		'{label}',
		'{id}',
		'{type}',
		'{amount}',
		'{format_amount}'
	);
} else {
	$product = $block->getSaleableItem();
}

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;


?>
<?php if ($block->hasSpecialPrice()): ?>
	<?php if($this->getRequest()->getFullActionName() != 'catalog_product_view') {
		$priceBlockRep = array(
			'old-price',
			__('Regular Price'),
			'old-price-' . $idSuffix,
			'oldPrice',
			$finalPrice,
			number_format($finalPrice, 2)
		);
		echo str_replace($priceBlockSearch, $priceBlockRep, $priceBlockTmp);
		$priceBlockRep = array(
			'special-price',
			__('Sale Price'),
			'product-price-' . $idSuffix,
			'finalPrice',
			$regPrice,
			number_format($regPrice, 2)
		);
		echo str_replace($priceBlockSearch, $priceBlockRep, $priceBlockTmp);
		
	} else {
	?>
	<span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Sale Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
	<?php } ?>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
