<!--@subject Your Magic Murals Discount Code & Newsletter Confirmation @-->
<!--@styles
body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
@-->
{{template config_path="design/email/header_template"}}

<p>Thank you for signing up to receive our newsletter and special offers.  Your first order discount code is: <strong>WELCOME10</strong>.</p>

<p>You can use this discount code for an additional 10% savings on any of the thousands of murals in our portfolio or on custom orders created from your own pictures and digital images.</p> 

<p>Your first special offer email will be sent shortly.  If you have multiple email tabs or stringent spam settings, you may need to add us to your address book to ensure you receive our offers.  We won't share your email address with others and we promise not to spam you.</p>

<p>Customer service is a top priority at Magic Murals.  Please feel free to call us Monday thruough Friday from 8:30 am to 4:30 pm ET at <a target="_blank" value="+18774487295" href="tel:1-877-448-7295">1-877-448-7295</a> or e-mail us at <a target="_blank" href="mailto:service@magicmurals.com">service@magicmurals.com</a> if there is anything we can do to help.</p>  

<br>

Warm regards,
The Magic Murals Team
{{template config_path="design/email/footer_template"}}