<p>Use this form to import multiple Testimonials at a time.</p>
<p>Zip your image files along with your import.csv file, then click the &quot;Browse&quot; button, select it, and click "Import"!</p>

<p>
<form method="POST" name="import_form" action="<?php echo $this->getUrl("*/*/importsave");?>" enctype="multipart/form-data">
	<?php echo $this->getBlockHtml('formkey')?>
	<p>Import File: <input type="file" name="import_file" id="import_file" /></p>
    <p><input type="submit" name="submit" value="Import" /></p>
</form>
</p>